# Generated by Django 3.0.8 on 2020-08-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhkh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
