# Generated by Django 3.0.8 on 2020-08-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhkh', '0002_person_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='building_type',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='cad_number',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zhkh.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='voting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zhkh.Voting'),
            preserve_default=False,
        ),
    ]
