# Generated by Django 3.0.8 on 2020-08-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhkh', '0005_auto_20200822_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='adress',
            new_name='flat',
        ),
    ]
