# Generated by Django 3.0.8 on 2020-08-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhkh', '0007_flat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='signature',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='person',
            name='publick_key',
            field=models.CharField(max_length=512),
        ),
    ]
