# Generated by Django 3.0.8 on 2020-08-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhkh', '0009_auto_20200822_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='publick_key',
            field=models.TextField(),
        ),
    ]
